# Initialize-v2.Upgrades.ps1 — Phase 1 Foundation Setup
# Spencer Proactive Agent v2.0 Upgrade — First Run

[CmdletBinding()]
param(
    [string]$ConfigPath = "C:\Users\spenc\.openclaw\workspace\skills\spencer-proactive-agent\config\spencer-agent-v2.json",
    [string]$Workspace = "C:\Users\spenc\.openclaw\workspace",
    [switch]$SkipCron,
    [switch]$Force
)

Write-Host "🛠️  Spencer Proactive Agent v2.0 — Phase 1 Initialization" -ForegroundColor Cyan
Write-Host "============================================================="

# Check config exists
if (-not (Test-Path $ConfigPath)) {
    Write-Error "Configuration not found at $ConfigPath. Run the generator first."
    exit 1
}

$config = Get-Content $ConfigPath -Raw | ConvertFrom-Json

# Validate workspace structure
$requiredDirs = @(
    "memory/topics",
    "memory/logs",
    "memory/private",
    "config",
    "scripts",
    "dashboard"
)

foreach ($dir in $requiredDirs) {
    $fullPath = Join-Path $Workspace $dir
    if (-not (Test-Path $fullPath)) {
        Write-Host "Creating directory: $dir"
        New-Item -ItemType Directory -Path $fullPath -Force | Out-Null
    }
}

# Create placeholder summary file
$summaryFile = Join-Path $Workspace "memory/topics/active-session.md"
if (-not (Test-Path $summaryFile)) {
    "# Active Session Summaries`n## Generated by Invisible Assistant`n" | Out-File -FilePath $summaryFile -Encoding UTF8
    Write-Host "✓ Created session summary log: memory/topics/active-session.md"
}

# Create buffer compression log
$compressionLog = Join-Path $Workspace "memory/logs/buffer-compression.log"
if (-not (Test-Path $compressionLog)) {
    "# Buffer Compression Log`n" | Out-File -FilePath $compressionLog -Encoding UTF8
    Write-Host "✓ Created compression log: memory/logs/buffer-compression.log"
}

# Create buffer archive directory
$archiveDir = Join-Path $Workspace "memory\buffer-archive"
if (-not (Test-Path $archiveDir)) {
    New-Item -ItemType Directory -Path $archiveDir -Force | Out-Null
    Write-Host "✓ Created buffer archive: memory/buffer-archive/"
}

# Feature summary
Write-Host "`n📋 Phase 1 Features Enabled:"
$enabled = $config.features | Get-Member -MemberType NoteProperty | Where-Object { $config.features.$($_.Name).enabled } | Select-Object -ExpandProperty Name
foreach ($feature in $enabled) {
    Write-Host "  ✅ $feature"
}
$disabled = $config.features | Get-Member -MemberType NoteProperty | Where-Object { -not $config.features.$($_.Name).enabled } | Select-Object -ExpandProperty Name
foreach ($feature in $disabled) {
    Write-Host "  ⚪ $feature (disabled)"
}

# Cron job installation
if (-not $SkipCron) {
    Write-Host "`n⏰ Installing cron jobs for Phase 1 features..."
    # We'll use the existing cron-jobs.json as base, but could add new ones
    # For now, just note that cron should be updated manually or via separate script
    Write-Host "  → Please run: .\scheduling\install-cron.ps1" -ForegroundColor Yellow
    Write-Host "  → Or manually add these jobs from config: buffer-monitor, empire-metrics, etc."
}
else {
    Write-Host "`n⏭️  Skipping cron installation (use -SkipCron if you want manual control)"
}

# Validation checks
Write-Host "`n🔍 Validation Checks:"
$sessionFile = Join-Path $Workspace "SESSION-STATE.md"
if (Test-Path $sessionFile) {
    $size = (Get-Item $sessionFile).Length
    $threshold = $config.features.'invisible-assistant'.bufferCompression.thresholdBytes
    $status = if ($size -gt $threshold) { "⚠️  > threshold ($threshold bytes)" } else { "✅ OK (< $threshold bytes)" }
    Write-Host "  SESSION-STATE.md: $size bytes — $status"
}
else {
    Write-Host "  SESSION-STATE.md: ❌ not found" -ForegroundColor Red
}

$compressor = Join-Path $Workspace "skills\spencer-proactive-agent\scripts\Compress-Buffer.ps1"
if (Test-Path $compressor) {
    Write-Host "  Compress-Buffer.ps1: ✅ present"
}
else {
    Write-Host "  Compress-Buffer.ps1: ❌ missing" -ForegroundColor Red
}

# Write initialization marker
$initMarker = Join-Path $Workspace "skills\spencer-proactive-agent\.initialized-v2"
$initData = @{
    timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    version = "2.0.0-alpha.1"
    configPath = $ConfigPath
    enabledFeatures = $enabled
} | ConvertTo-Json -Depth 3
Set-Content -Path $initMarker -Value $initData -Encoding UTF8

Write-Host "`n✅ Phase 1 initialization complete!"
Write-Host "`n📖 Next steps:"
Write-Host "  1. Review config: $ConfigPath"
Write-Host "  2. Install cron jobs (if not skipped): .\scheduling\install-cron.ps1"
Write-Host "  3. Test buffer compression: .\scripts\Compress-Buffer.ps1"
Write-Host "  4. Monitor logs: memory/logs/buffer-compression.log"
Write-Host "  5. Check feature flags: $initMarker"
Write-Host "`n🗺️  Atlas signing off — building your co-pilot, one upgrade at a time."